name: aifact
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - anthropic=0.42.0=pyhd8ed1ab_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h2bbff1b_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - async-lru=2.0.4=py312haa95532_0
  - babel=2.11.0=py312haa95532_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312haa95532_0
  - bottleneck=1.4.2=py312h4b0e54e_0
  - brotli-python=1.0.9=py312hd77b12b_8
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2024.12.31=haa95532_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cffi=1.17.1=py312h827c3e9_0
  - colorama=0.4.6=py312haa95532_0
  - comm=0.2.1=py312haa95532_0
  - debugpy=1.6.7=py312hd77b12b_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distro=1.9.0=py312haa95532_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.6.4=h8ddb27b_0
  - h11=0.14.0=py312haa95532_0
  - icu=73.1=h6c2663c_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - ipykernel=6.29.5=py312haa95532_0
  - ipython=8.30.0=py312haa95532_0
  - ipywidgets=8.1.5=py312haa95532_0
  - jedi=0.19.2=py312haa95532_0
  - jpeg=9e=h827c3e9_3
  - jsonschema=4.23.0=py312haa95532_0
  - jupyter=1.0.0=py312haa95532_9
  - jupyter-lsp=2.2.0=py312haa95532_0
  - jupyter_client=8.6.0=py312haa95532_0
  - jupyter_console=6.6.3=py312haa95532_1
  - jupyter_core=5.7.2=py312haa95532_0
  - jupyter_events=0.10.0=py312haa95532_0
  - jupyter_server=2.14.1=py312haa95532_0
  - jupyter_server_terminals=0.4.4=py312haa95532_1
  - jupyterlab=4.2.5=py312haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=2.27.3=py312haa95532_0
  - jupyterlab_widgets=3.0.13=py312haa95532_0
  - krb5=1.20.1=h5b6d351_0
  - libclang=14.0.6=default_hb5a9fac_2
  - libclang13=14.0.6=default_h8e68704_2
  - libexpat=2.6.4=he0c23c2_0
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.39=h8cc25b3_0
  - libpq=17.2=h70ee33d_0
  - libsodium=1.0.18=h62dcd97_0
  - libsqlite=3.48.0=h67fdade_0
  - libuv=1.48.0=h827c3e9_0
  - libzlib=1.2.13=h2466b09_6
  - lz4-c=1.9.4=h2bbff1b_1
  - matplotlib-inline=0.1.6=py312haa95532_0
  - mistune=2.0.4=py312haa95532_0
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py312h827c3e9_2
  - mkl_fft=1.3.11=py312h827c3e9_0
  - mkl_random=1.2.8=py312h0158946_0
  - mpmath=1.3.0=py312haa95532_0
  - nbclient=0.8.0=py312haa95532_0
  - nbconvert=7.16.4=py312haa95532_0
  - nbformat=5.10.4=py312haa95532_0
  - nest-asyncio=1.6.0=py312haa95532_0
  - notebook=7.2.2=py312haa95532_1
  - notebook-shim=0.2.3=py312haa95532_0
  - numexpr=2.10.1=py312h4cd664f_0
  - openssl=3.4.0=ha4e3fda_1
  - overrides=7.4.0=py312haa95532_0
  - packaging=24.2=py312haa95532_0
  - pandas=2.2.3=py312h5da7b33_0
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312haa95532_0
  - platformdirs=3.10.0=py312haa95532_0
  - ply=3.11=py312haa95532_1
  - prometheus_client=0.21.0=py312haa95532_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pyqt=5.15.10=py312hd77b12b_0
  - pyqt5-sip=12.13.0=py312h2bbff1b_0
  - pysocks=1.7.1=py312haa95532_0
  - python=3.12.3=h2628c8c_0_cpython
  - python-dateutil=2.9.0post0=py312haa95532_2
  - python-fastjsonschema=2.20.0=py312haa95532_0
  - python-json-logger=3.2.1=py312haa95532_0
  - python-tzdata=2023.3=pyhd3eb1b0_0
  - python_abi=3.12=5_cp312
  - pytorch=2.3.1=cpu_py312h0ce1571_0
  - pytz=2024.1=py312haa95532_0
  - pywin32=305=py312h2bbff1b_0
  - pywinpty=2.0.14=py312h72d21ff_0
  - pyyaml=6.0.2=py312h827c3e9_0
  - pyzmq=26.2.0=py312h5da7b33_0
  - qt-main=5.15.2=h19c9488_11
  - qtconsole=5.6.0=py312haa95532_0
  - qtpy=2.4.1=py312haa95532_0
  - requests=2.32.3=py312haa95532_1
  - rfc3339-validator=0.1.4=py312haa95532_0
  - rfc3986-validator=0.1.1=py312haa95532_0
  - send2trash=1.8.2=py312haa95532_0
  - setuptools=72.1.0=py312haa95532_0
  - sip=6.7.12=py312hd77b12b_0
  - sqlite=3.45.3=h2bbff1b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - sympy=1.13.3=py312haa95532_0
  - tbb=2021.8.0=h59b6b97_0
  - terminado=0.17.1=py312haa95532_0
  - tinycss2=1.2.1=py312haa95532_0
  - tk=8.6.14=h0416ee5_0
  - tornado=6.4.2=py312h827c3e9_0
  - traitlets=5.14.3=py312haa95532_0
  - tree_sitter_languages=1.10.2=py312he70551f_1
  - typing-extensions=4.12.2=py312haa95532_0
  - typing_extensions=4.12.2=py312haa95532_0
  - tzdata=2024b=h04d1e81_0
  - ucrt=10.0.22621.0=h57928b3_1
  - vc=14.40=haa95532_2
  - vc14_runtime=14.42.34433=he29a5d6_23
  - vs2015_runtime=14.42.34433=hdffcdeb_23
  - webencodings=0.5.1=py312haa95532_2
  - websocket-client=1.8.0=py312haa95532_0
  - wheel=0.44.0=py312haa95532_0
  - widgetsnbextension=4.0.13=py312haa95532_0
  - win_inet_pton=1.1.0=py312haa95532_0
  - winpty=0.4.3=4
  - xz=5.4.6=h8cc25b3_1
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.5=hd77b12b_0
  - zlib=1.2.13=h2466b09_6
  - zstd=1.5.6=h8880b57_0
  - pip:
      - aider==0.2.6
      - aider-chat==0.75.1
      - aider-install==0.1.2
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - attrs==25.1.0
      - backoff==2.2.1
      - beautifulsoup4==4.13.3
      - black==24.10.0
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - configargparse==1.7
      - configparser==7.1.0
      - diff-match-patch==20241021
      - diskcache==5.6.3
      - filelock==3.17.0
      - flake8==7.1.2
      - frozenlist==1.5.0
      - fsspec==2025.2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grep-ast==0.6.1
      - httpcore==1.0.7
      - httpx==0.28.1
      - huggingface-hub==0.29.0
      - idna==3.10
      - importlib-metadata==7.2.1
      - importlib-resources==6.5.2
      - jinja2==3.1.5
      - jiter==0.8.2
      - json5==0.10.0
      - jsonschema-specifications==2024.10.1
      - kaggle==1.6.17
      - kowpy==0.1.0
      - litellm==1.61.9
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mixpanel==4.10.1
      - monotonic==1.6
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - networkx==3.2.1
      - numpy==1.26.4
      - openai==1.63.2
      - pathspec==0.12.1
      - pexpect==4.9.0
      - pillow==10.4.0
      - pip==25.0.1
      - posthog==3.14.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyflakes==3.2.0
      - pygments==2.19.1
      - pypandoc==1.15
      - pyperclip==1.9.0
      - python-dotenv==1.0.1
      - python-slugify==8.0.4
      - referencing==0.36.2
      - regex==2024.11.6
      - rich==13.9.4
      - rpds-py==0.22.3
      - ruff==0.8.6
      - safetensors==0.5.2
      - scipy==1.13.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - socksio==1.0.0
      - sounddevice==0.5.1
      - soundfile==0.13.1
      - soupsieve==2.6
      - text-unidecode==1.3
      - tiktoken==0.9.0
      - tokenizers==0.21.0
      - tqdm==4.67.1
      - transformers==4.43.4
      - tree-sitter==0.21.3
      - tree-sitter-cpp==0.23.4
      - tree-sitter-java==0.23.5
      - tree-sitter-javascript==0.23.1
      - tree-sitter-python==0.23.6
      - tree-sitter-typescript==0.23.2
      - urllib3==2.3.0
      - uv==0.5.11
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - yarl==1.18.3
      - zipp==3.21.0
prefix: C:\Users\rober\anaconda3\envs\aifact
